# -*- coding: utf-8 -*-
"""lab10.doai

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10dVFHL8M7dZdeZ0D_tgLT5zIh3gj1TRo
"""

def is_magic_square(square):
    magic_sum = sum(square[0])
    # Check rows and columns
    for i in range(3):
        if sum(square[i]) != magic_sum:
            return False
        col_sum = sum(square[j][i] for j in range(3))
        if col_sum != magic_sum:
            return False
    # Check diagonals
    if sum(square[i][i] for i in range(3)) != magic_sum:
        return False
    if sum(square[i][2 - i] for i in range(3)) != magic_sum:
        return False
    return True

def print_square(square):
    for row in square:
        print(" ".join(map(str, row)))

def magic_square_game():
    square = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
    numbers = set(range(1, 10))
    print("Welcome to the 3x3 Magic Square Game!")
    print("Enter numbers from 1 to 9 to fill the square.")
    for i in range(3):
        for j in range(3):
            while True:
                try:
                    num = int(input(f"Enter number for row {i+1}, column {j+1}: "))
                    if num in numbers:
                        numbers.remove(num)
                        square[i][j] = num
                        break
                    else:
                        print("Invalid number! Number should be unique and between 1 to 9.")
                except ValueError:
                    print("Invalid input! Please enter a number.")

    print("Your square:")
    print_square(square)

    if is_magic_square(square):
        print("Congratulations! You've created a magic square!")
    else:
        print("Sorry! Not a magic square.")

magic_square_game()
7