# -*- coding: utf-8 -*-
"""Lab2-DOAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iyQDuqJPb9ruAh8E0rqRrMCUykRb4MJH
"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline

emails = [
    ("Hey, are we still meeting tomorrow?", "Yes, we are still meeting tomorrow."),
    ("Could you please send me the report?", "Sure, I'll send it to you shortly."),
    ("Do you have any updates on the project?", "Yes, we've made significant progress."),
]

X_train = [email[0] for email in emails]
y_train = [email[1] for email in emails]

model = make_pipeline(
    TfidfVectorizer(),
    MultinomialNB()
)

model.fit(X_train, y_train)

def suggest_reply(email_content):
    predicted_reply = model.predict([email_content])[0]
    return predicted_reply

test_email = "Could you please send me the report?"
suggested_reply = suggest_reply(test_email)
print("Suggested reply:", suggested_reply)